import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/src/shared/theme';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: { padding: 4 },
  headerTitle: { fontSize: 18, fontWeight: '600', color: colors.text, flex: 1, textAlign: 'center', marginLeft: 8 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  headerButton: { padding: 4 },
  saveButton: { padding: 4, width: 32, alignItems: 'center' },
  content: { flex: 1 },
  contentContainer: { padding: 16, paddingBottom: 32 },
  section: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceHighlight,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  bookContainer: { flexDirection: 'row', gap: 16, marginBottom: 16 },
  bookCoverImage: { width: 100, height: 150, borderRadius: 8 },
  bookInfo: { flex: 1, justifyContent: 'center' },
  bookTitleText: { fontSize: 18, fontWeight: '600', color: colors.text, marginBottom: 4 },
  bookAuthorText: { fontSize: 14, color: colors.primary, marginBottom: 12 },
  bookMeta: { flexDirection: 'row', gap: 16, marginBottom: 12 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { fontSize: 12, color: colors.textTertiary },
  genreBadge: {
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: 'rgba(32, 184, 205, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  genreText: { fontSize: 11, color: colors.primary, fontWeight: '500' },
  badgeContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1, alignSelf: 'flex-start' },
  statusText: { fontSize: 11, fontWeight: '600' },
  bookDesc: { fontSize: 13, lineHeight: 20, color: colors.textSecondary },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  sectionTitle: { fontSize: 14, fontWeight: '600', color: colors.text },
  authorName: { fontSize: 14, fontWeight: '500', color: colors.primary, marginBottom: 8 },
  authorDesc: { fontSize: 13, lineHeight: 20, color: colors.textSecondary },
  savedQuotesList: { gap: 12 },
  savedQuoteCard: { backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: colors.surfaceHighlight, padding: 12 },
  savedQuoteText: { fontSize: 14, lineHeight: 22, color: colors.text, fontStyle: 'italic', marginBottom: 8 },
  savedQuoteMeta: { flexDirection: 'row', justifyContent: 'space-between' },
  savedQuoteAuthor: { fontSize: 12, color: colors.primary },
  savedQuoteDate: { fontSize: 12, color: colors.textTertiary },
  similarBooksContainer: { marginHorizontal: -8 },
  similarBookItem: { width: 90, marginHorizontal: 8 },
  similarBookCover: { width: 90, height: 135, borderRadius: 8, marginBottom: 8 },
  similarBookTitle: { fontSize: 12, color: colors.text, textAlign: 'center', lineHeight: 16 },
  placeholderSection: {
    borderWidth: 1,
    borderColor: colors.surfaceHighlight,
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 24,
    minHeight: 140,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  placeholderIcon: { marginBottom: 8 },
  placeholderText: { color: colors.textSecondary, fontSize: 14, fontWeight: '600' },
  removableWrapper: { position: 'relative' },
  removeButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  gridSection: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceHighlight,
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
  },
  errorText: { color: colors.text, textAlign: 'center', marginTop: 50 },
  notesInput: {
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
    color: colors.inputText,
    fontSize: 13,
    minHeight: 120,
  },
  userRatingContainer: { marginBottom: 16, alignItems: 'center' },
  subTitle: { fontSize: 13, color: colors.textSecondary, marginBottom: 8, alignSelf: 'flex-start' },
  starRow: { flexDirection: 'row', gap: 8 },
  commentInputContainer: { marginBottom: 20 },
  commentInput: {
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
    color: colors.inputText,
    fontSize: 13,
    minHeight: 80,
  },
  reviewsList: {
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 16,
  },
  reviewItem: { backgroundColor: colors.background, borderRadius: 12, padding: 12 },
  reviewHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  reviewerInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  reviewerAvatar: { width: 24, height: 24, borderRadius: 12 },
  reviewerName: { fontSize: 12, color: colors.text, fontWeight: '500' },
  reviewDate: { fontSize: 11, color: colors.textTertiary },
  reviewRating: { flexDirection: 'row', gap: 2, marginBottom: 6 },
  reviewComment: { fontSize: 13, color: colors.textSecondary, lineHeight: 18 },
  publishButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 12,
    alignSelf: 'flex-end',
    paddingHorizontal: 16,
    gap: 6,
  },
  publishButtonText: { color: '#000', fontSize: 12, fontWeight: '600' },
  seeAllReviewsButton: { alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: colors.border, marginTop: 8 },
  seeAllReviewsText: { color: colors.primary, fontSize: 13, fontWeight: '500' },
  modalContainer: { flex: 1, backgroundColor: colors.background },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
  modalTitle: { fontSize: 18, fontWeight: '600', color: colors.text },
  modalCloseButton: { padding: 4 },
  modalContent: { padding: 16, gap: 16 },
  modalReviewItem: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: colors.surfaceHighlight },
  reviewerAvatarLarge: { width: 32, height: 32, borderRadius: 16 },
  reviewerNameLarge: { fontSize: 14, fontWeight: '600', color: colors.text },
  reviewCommentLarge: { fontSize: 14, color: colors.text, lineHeight: 22, marginTop: 8 },
  buyLinksList: { gap: 12 },
  buyLinkItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  buyLinkInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  buyLinkStore: { color: '#FFF', fontSize: 14, fontWeight: '500' },
  buyLinkPrice: { color: colors.primary, fontSize: 14, fontWeight: '600' },
  tabContainer: { flexDirection: 'row', marginBottom: 16, borderBottomWidth: 1, borderBottomColor: colors.surfaceHighlight },
  tabButton: { flex: 1, paddingVertical: 12, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  activeTabButton: { borderBottomColor: colors.primary },
  tabText: { fontSize: 14, fontWeight: '500', color: colors.textTertiary },
  activeTabText: { color: colors.text, fontWeight: '600' },
});
