require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, '15.5'

prepare_react_native_project!

target 'Quotex' do
  config = use_native_modules!
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  # Pods additionnels éventuels (exemple)

end

post_install do |installer|
  react_native_post_install(installer)
  # Allow non-modular includes in pods to avoid "non-modular-include-in-framework-module" errors
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
